### ISSUE TITLE
schemes file

### ISSUE THREAD

**Issue by pbnj** [eendroroy/alacritty-theme#14]
Alacritty supports a [`schemes`](https://github.com/alacritty/alacritty/wiki/Color-schemes#multiple-schemes) which contains any arbitrary amount of themes that users can select  from in `colors:`

Example:
```yaml
scheme:
  afterglow: &afterglow
    primary:
      background: ....
      foreground: ...
    ...

  argonaut: &argonaut
    ...

  ayu_dark: &ayu_dark
    ...

colors: *ayu_dark
```

Would you be willing to accept a PR that merges all the themes into a `schemes.yaml` file?
